apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.component }}
  labels:
    appName: {{ .Values.component }}
    projectName: {{ .Chart.Name }}
spec:
  {{ if .Values.initContainers.enabled }}
  volumes:
    - name: vault-secret
      emptyDir: { }

  initContainers:
    - name: get-secret
      image: pavanidevops78/kubernetes:v8
      env:
        - name: VAULT_ADDR
          value: "https://vault-internal.pdevops78.online:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: common/common
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"

      volumeMounts:
        - name: vault-secret
          mountPath: /data
  {{ end }}
    - name: schema
      image: pavanidevops78/kubernetes:b4
      volumeMounts:
        - name: vault-secret
          mountPath: /data
  containers:
    - name: backend
      image: pavanidevops78/kubernetes:{{ .Values.appVersion }}
  {{ if .Values.initContainers.enabled }}
      volumeMounts:
        - name: vault-secret
          mountPath: /data
  {{ end }}


# ClusterIP service type is by default




